### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by stellanhaglund** [pofider/phantom-html-to-pdf#20]
Trying to run this in docker gives me

/node_modules/phantom-html-to-pdf/lib/conversion.js:83
if (opt.phantomPath) {
^

TypeError: Cannot read property 'phantomPath' of undefined
at module.exports (/node_modules/phantom-html-to-pdf/lib/conversion.js:83:12)
at Object. (/lib/index.js:11:45)
at Module._compile (module.js:397:26)
at Object.Module._extensions..js (module.js:404:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/example/index.js:2:15)
at Module._compile (module.js:397:26)

any ideas?

**Comment by stellanhaglund** [comment]
IonicaBizau/nodeice#13

**Comment by bjrmatos** [comment]
ups! a bug was introduced in the latest version, let met update it..

**Comment by bjrmatos** [comment]
ok, fixed! lets wait for a new release cc @pofider

**Comment by pofider** [comment]
Somehow I missed this when I was reviewing last pull request. Thank you for fix.

Released in 0.3.5
